# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of event', max_length=200)),
                ('description', models.TextField(help_text='description of event')),
                ('event_date', models.DateTimeField(help_text='The datetime of the event')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The datetime event was created')),
                ('participants', models.PositiveIntegerField(help_text='The number of participants for this event')),
                ('owner', models.ForeignKey(help_text='owner of event', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The datetime rsvp was added')),
                ('event', models.ForeignKey(help_text="event user rsvp'ed", on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(help_text="user who rsvp'ed", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set([('user', 'event')]),
        ),
    ]
